#
# Module manifest for module 'PSRedSeal'
#
# Generated by: David F. Severski
#
# Generated on: 10/31/2012
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSRedSeal.psm1'

# Version number of this module.
ModuleVersion = '1.2'

# ID used to uniquely identify this module
GUID = 'eb22a46c-a0bc-48ad-917b-4b232476c4ba'

# Author of this module
Author = 'David F. Severski'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = '(c) 2016 David F. Severski. All rights reserved.'

# Description of the functionality provided by this module
# Description = ''

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = 'Connect-RSServer', 'ConvertFrom-RSDate', 'ConvertTo-RSData', 'Get-RSAdminTaskHistory', 'Get-RSCollectionTask', 'Get-RSComputer', 'Get-RSConnections', 'Get-RSDevice', 'Get-RSDeviceDetail', 'Get-RSGroup', 'Get-RSHost', 'Get-RSHostDetail', 'Get-RSMetricsDetails', 'Get-RSMetricsGroup', 'Get-RSModelIssue', 'Get-RSReportList', 'Get-RSSubnet', 'Get-RSSystemLicense', 'Get-RSSystemStatus', 'Get-RSView', 'Import-RSScanFile', 'Invoke-RSDataQuery', 'Invoke-RSQuery', 'New-RSGroup', 'New-RSHost', 'Read-RSAccessResult', 'Read-RSImpactResult', 'Read-RSPathResult', 'Read-RSReport', 'Read-RSThreatResult', 'Remove-RSGroup', 'Remove-RSHost', 'Set-RSDataQuery', 'Set-RSGroup', 'Set-RSHost', 'Set-RSQueryTarget', 'Start-RSAdminTask', 'Start-RSAnalysis'

# Cmdlets to export from this module
CmdletsToExport = ''

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module.
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}